### ISSUE TITLE
Final changes to survey

### ISSUE THREAD

**Issue by LucyMcGowan** [wfu-dmds/teaching-r-study#11]
- [ ] Update to 150 total users
- [x] update assessments 2 and 3 with new shiny questions - send the answers to dropbox (check that this is working)
- [x] create a "Turn in Survey" button
- [x] create an additional page that has the username in the URL that requests the user's email address if they'd like a $5 gift card
- [x] create learnr-a and learnr-b that they get sent to from the survey based on what group they are in swapping the order of base and tidyverse so:
*  A - intro, assessment, tidy, tidy, tidy, assessment, base, base, base, assessment
* B - intro, assessment, base, base, base, assessment, tidy, tidy, tidy, assessment
- [x] test that the urls /survey are working well

**Comment by jdtrat** [comment]
Oops -- didn't mean to close this.

**Comment by jdtrat** [comment]
@LucyMcGowan Do you know how to get rid of the "Previous Topic" button from the learnr modules? I haven't come across anything that would help with that (pictured is the end of assessment 3).

![Screen Shot 2021-02-04 at 8 45 15 PM](https://user-images.githubusercontent.com/51417262/106978248-e51af000-6729-11eb-8ce7-083669435a76.png)

**Comment by LucyMcGowan** [comment]
I don’t & last time I looked it was hard coded in. I think it’s fine to leave it and just add a “I’m finished with the course” button - they may want to go back before they decide they’re finished for example

**Comment by jdtrat** [comment]
Fair! I have only figured out how to place a "Finish Survey" button above that. Do you think that's okay? If not, what would you suggest? (I'm sure we can change the CSS of that button).

![Screen Shot 2021-02-04 at 9 20 01 PM](https://user-images.githubusercontent.com/51417262/106980746-bfdcb080-672e-11eb-902f-44e06825f890.png)

**Comment by LucyMcGowan** [comment]
Above is great!

**Comment by jdtrat** [comment]
This is what I'm thinking. For whatever reason, `onclick` will not work, so I have another modal pop up that won't go away.
Upon submission, a .rds file gets uploaded with a tibble containing the username and email. Let me know if I should push the changes or change anything!

![complete_session](https://user-images.githubusercontent.com/51417262/106986061-8f9a0f80-6738-11eb-87d0-74e1b4c7f76b.gif)

**Comment by LucyMcGowan** [comment]
This looks great to me, thanks!

**Comment by jdtrat** [comment]
Changing usernames to 150 should be done right before launch (as they will get used if we are still testing it). We should all test the urls/survey more formally, but from what I can tell they all work!

**Comment by jdtrat** [comment]
You can run through the task here: http://wfudatasciencelab.shinyapps.io/learnr-consent/

**Comment by nuripark10** [comment]
There is an error in tidy_reading data module. For the exercise where the solution is "read_csv("data/airquality.csv"))", I get an error "cannot open the connection to 'https://raw.githubusercontent.com/wfu-dmds/teaching-r-study/master/learnr-module/data/airquality.csv'"

**Comment by nuripark10** [comment]
2. Solutions are visible for exercises in tidy modules. Did we mean it? 
3. Tidy manipulating module -> pipe exercise "Using the flights data, find the the flights average distance grouped by year, origin, dest, and arr_delay." -> answer is correct but module says it is wrong.

**Comment by LucyMcGowan** [comment]
@nuripark10, I've fixed the first issue (with reading in the `airquality` data). What do you mean the solutions are visible for the exercises in tidy modules? I didn't see the solutions, but maybe I've missed something! For (3), what answer did you try? I did:

```
flights %>% 
  filter(arr_delay <= 120) %>%
  select(dep_time, sched_dep_time)
```

And it worked.
