### ISSUE TITLE
Errors in LearnR module

### ISSUE THREAD

**Issue by nuripark10** [wfu-dmds/teaching-r-study#6]
1. Assessment 
- still gives me "incorrect" for my answer to "read.csv" 
- "Error: An error has occurred. Check your logs or contact the app author for clarification" for other questions in the assessment

2. Base R
- Vectors, Lists, and Data Frames: logical vectors still give "object 'x' not found". 
- Reading data exercise gives an error "cannot open the connection"

**Comment by LucyMcGowan** [comment]
For 1, I can't seem to replicate that 🤔 Here is what I see:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/8431897/97086880-0f6df500-15f4-11eb-9bc8-c60636247917.png">

**Comment by LucyMcGowan** [comment]
I don't see the errors for (2) either - are you downloading the most recent version from GitHub and running it locally?
