### ISSUE TITLE
Update consent, demographics, and learnr module to incorporate user ids and deploy to 

### ISSUE THREAD

**Issue by LucyMcGowan** [wfu-dmds/teaching-r-study#9]
@jdtrat: copying this over from our email

With the new changes, can you please update the learnr study by:

- [x]  Add code to `consent-app.R` to create the consent page and deploy this to wfudatasciencelab.shinyapps.io/learnr-consent 
   - this should include the ability to randomize and create the user IDs for folks that consent and then direct them to the demographic survey url

- [x] Add code to `survey-app.R` to create the demographics survey and deploy this to wfudatasciencelab.shinyapps.io/learnr-demographics 
    - this should include the ability to get the user's ID and then send them to the learnr application after completing the demographics survey

- [x] Update the code in the learnr-module folder to:
   1. Find the user's ID in the URL
   2. Save the users data to dropbox
   3. Add inputs in the `assement.Rmd` file to collect data on the likert scale questions (and potentially change the numeric questions to use shiny rather than learnr as the backend)
   4. Deploy to wfudatasciencelab.shinyapps.io/learnr

**Comment by jdtrat** [comment]
@LucyMcGowan Should I use the original `consent.html` and `home.html` documents? If so, is it okay to bundle the apps in a folder with the traditional Shiny structure?

**Comment by LucyMcGowan** [comment]
Yes! Sorry I should have left those in the repo - do you have the locally? I can push them if not. And yes! Feel free to have them in their own folders

**Comment by jdtrat** [comment]
No worries! I'll grab them from the GitHub history.

**Comment by jdtrat** [comment]
Please see latest commit. All are addressed and when tested was functional. I hope to clean up the code but wanted to get this to you ASAP. You can walk-through it yourself [here](https://wfudatasciencelab.shinyapps.io/learnr-consent).

**Comment by LucyMcGowan** [comment]
This looks great! The only thing I didn’t see added were inputs for the likert scale questions for the assessment. I tried it on mobile too and the survey came out a bit wonky (but this is definitely low priority, just thought I’d mention so we can track it) 

![0454537D-5C9B-4D02-8C76-3B0E123BFBE6](https://user-images.githubusercontent.com/8431897/106393945-e6fe4f80-63c7-11eb-8ca4-a3e56915d711.jpeg)

**Comment by jdtrat** [comment]
I'm not sure what you mean re: likert questions/assessment. For each assessment, am I supposed to have a include a shinysurvey that tracks their responses?

Also, that's a {shinysurveys} issue. The scaling doesn't work properly. If you have a chance, I'd appreciate your taking a look at the CSS file!

**Comment by jdtrat** [comment]
> I'm not sure what you mean re: likert questions/assessment. For each assessment, am I supposed to have a include a shinysurvey that tracks their responses?
> 
> Also, that's a {shinysurveys} issue. The scaling doesn't work properly. If you have a chance, I'd appreciate your taking a look at the CSS file!

The sass file is [here](https://github.com/jdtrat/shinysurveys/blob/main/inst/render_survey.scss) and you can see a demo (for browser inspection) [here](https://jdtrat-apps.shinyapps.io/shinysurveys-demo-survey/).

**Comment by LucyMcGowan** [comment]
Ah I meant just adding a shiny element that will save to the same Dropbox folder with their username for the first 3 questions in assessment.Rmd (right now the questions are there but no way to input responses)

**Comment by jdtrat** [comment]
Should the same exercises appear on each assessment or just the questions?

**Comment by LucyMcGowan** [comment]
Yes! All 3 assessments are exactly the same

**Comment by jdtrat** [comment]
Just added that assessment functionality. You can see the files in the Dropbox. We should do some more testing, but it seems to work fine!

**Comment by jdtrat** [comment]
> This looks great! The only thing I didn’t see added were inputs for the likert scale questions for the assessment. I tried it on mobile too and the survey came out a bit wonky (but this is definitely low priority, just thought I’d mention so we can track it)
> 
> ![0454537D-5C9B-4D02-8C76-3B0E123BFBE6](https://user-images.githubusercontent.com/8431897/106393945-e6fe4f80-63c7-11eb-8ca4-a3e56915d711.jpeg)

This was fixed in the latest update to {shinysurveys} and I've redeployed the survey-app!
